//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpEntities : DbContext
    {
        private static HelpEntities _context;
        public HelpEntities()
            : base("name=HelpEntities")
        {
        }
        public static HelpEntities GetContext()
        {
            if (_context == null)
                _context = new HelpEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Paid_Courses> Paid_Courses { get; set; }
        public virtual DbSet<PaidCourseType> PaidCourseType { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
        public virtual DbSet<SupervisorAndTrainee> SupervisorAndTrainee { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<Trainee> Trainee { get; set; }
        public virtual DbSet<Certification> Certification { get; set; }
    }
}
