//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paid_Courses
    {
        public long Id_Paid_Courses { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public long Id_PaidCourseType { get; set; }
    
        public virtual PaidCourseType PaidCourseType { get; set; }
    }
}
